apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: mentorat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mentorat
  template:
    metadata:
      labels:
        app: mentorat
    spec:
      containers:
      - name: mentorat
        image: raresh25508/pregatit-demo-app-python
        imagePullPolicy: Never
        ports:
        - containerPort: 5000      

---
apiVersion: v1
kind: Service
metadata:
  name: app-deployment
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mentorat
  type: NodePort

---
  apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: Service
subsets:
  - addresses:
      - ip: 192.0.2.42
    ports:
      - port: 5000